### ISSUE TITLE
Reference to identifiant is wrong

### ISSUE THREAD

**Issue by zhenleibb** [Kevin-Lee/maven2sbt#149]
# Bug
Given input pom.xml contains this lines:
```
  <properties>
    <revision.base>0.7.0</revision.base>
    <revision>${revision.base}-SNAPSHOT</revision>
```
When compile it
Then the output build.sbt contains this lines:
```
val revisionBase = "0.7.0"
val revision = "${revision.base}-SNAPSHOT" // expected s"${revisionBase}-SNAPSHOT"
```

# Cause
- String interpolation is wrong
- Don't use scala variable version of identifiant, still use maven version of identifiant

**Comment by Kevin-Lee** [comment]
@zhenleibb 🙂👍
